"""Genesis exploration: raise, approach, grasp and lift a liquid-filled holder.

Derived from oa_baseline.py now called oa_full_sim.py. Uses IK and joint interpolation, without RRT.
Physical collisions still apply, but the motion does not plan around obstacles.
"""

import argparse
import atexit
import csv
import time
from pathlib import Path

import genesis as gs
import numpy as np
from pxr import Usd, UsdGeom
from scipy.spatial.transform import Rotation

import scooping_kinematics as sk
from trajectory_diagnostics import Recorder

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--headless', action='store_true', help='Disable viewer/debug drawing and exit after playback')
parser.add_argument('--diagnostics', type=Path, help='Directory for CSVs, plots and timing reports')
parser.add_argument('--max-frames', type=int, help='Limit recorded frames for a short smoke test')
parser.add_argument('--no-liquid', action='store_true', help='Rigid-only comparison; changes physics')
parser.add_argument('--backend', choices=['gpu', 'cpu'], default='gpu')
parser.add_argument('--scooping-point', type=float, nargs=3, default=sk.SELECTED_POINT.tolist(),
                    metavar=('X', 'Y', 'Z'), help='Where the first Bowl_center sample of scooping_kinematics.TRAJ_CSV is moved to (pure translation); '
                    'default is the screened placement')
args = parser.parse_args()
phase_timings = []
def report_phase(name, started):
    elapsed = time.perf_counter() - started
    phase_timings.append((name, elapsed))
    print(f'[Timing] {name}: {elapsed:.3f} s', flush=True)

ASSETS_DIR = Path(__file__).resolve().parent.parent / "assets"
OPENARM_USD = ASSETS_DIR / "openarm_bimanual" / "openarm_spoon_w_o_markers.usd"
BOWL_USD = ASSETS_DIR / "props" / "Bowl_holder_w_o_marker.usd"
# Generated by feeding_mapping.py; the replay reads only this file.
TRAJ_CSV = sk.TRAJ_CSV
if args.diagnostics:
    args.diagnostics.mkdir(parents=True, exist_ok=True)

# Place the handle near the table edge for finger clearance; the bowl stays over the table.
# World placement. Dimensions below are measured in the unmarked holder STL frame (m).
TABLE_TOP_Z = 0.30
BOWL_CENTER_XY = np.array([0.43, 0.30]) # Circular opening center, in WORLD X/Y.
BOWL_AXIS_LOCAL_X = 0.1549              # Circular bowl's central axis along local X.
HOLDER_BOTTOM_LOCAL_Y = -0.0279         # Underside; local Y becomes world height.
BOWL_RIM_LOCAL_Y = 0.0191
BLOCK_MID_LOCAL_Y = 0.0077              # Midpoint of block's local Y bounds.
BOWL_POS = (float(BOWL_CENTER_XY[0] - BOWL_AXIS_LOCAL_X),
            float(BOWL_CENTER_XY[1]), TABLE_TOP_Z - HOLDER_BOTTOM_LOCAL_Y)
BOWL_EULER = (90, 0, 0)                 # Opening faces up: local +Y -> world +Z.
GRASP_HEIGHT_OFFSET = 0.025             # Jaws extend ~27 mm below the reference point.
# Grasp 20 mm from the free end, 25 mm above mid-height, on the width centerline.
BLOCK_GRASP_LOCAL = np.array([0.020, BLOCK_MID_LOCAL_Y + GRASP_HEIGHT_OFFSET, 0.0])
BOWL_RIM_Z = BOWL_POS[2] + BOWL_RIM_LOCAL_Y
LIQUID_SIZE = (0.06, 0.06, 0.06)
LIQUID_POS = (BOWL_CENTER_XY[0], BOWL_CENTER_XY[1], BOWL_RIM_Z + 0.03 + LIQUID_SIZE[2] / 2)

SCOOPING_POINT = np.array(args.scooping_point)

gs.init(backend=gs.gpu if args.backend == "gpu" else gs.cpu, seed=0)
scene = gs.Scene(
    viewer_options=gs.options.ViewerOptions(
        camera_pos=(1.49, 0.68, 0.96), camera_lookat=(0.35, 0.10, 0.33),
        enable_gui=not args.headless,
    ),
    sim_options=gs.options.SimOptions(dt=0.004, substeps=60),
    sph_options=gs.options.SPHOptions(
        particle_size=0.006, lower_bound=(0.1, -0.5, 0.0), upper_bound=(1.0, 0.5, 0.9),
    ),
    vis_options=gs.options.VisOptions(visualize_sph_boundary=True),
    show_viewer=not args.headless,
    profiling_options=gs.options.ProfilingOptions(show_FPS=not args.headless),
)
plane = scene.add_entity(gs.morphs.Plane(), name="Plane")
openarm = scene.add_entity(
    gs.morphs.USD(file=str(OPENARM_USD), fixed=True),
    # Cancel robot self-weight so the position controller tracks the grasp more closely.
    material=gs.materials.Rigid(sdf_min_res=64, sdf_max_res=256, gravity_compensation=1.0), name="OpenArm",
)
table = scene.add_entity(
    gs.morphs.USD(file=str(ASSETS_DIR / "props" / "table.usd"),
                  pos=(0.6, 0, 0), euler=(0, 0, 90), fixed=True),
    name="Table",
)
# Source components are watertight: preserve them instead of wrapping/merging them.
# fixed=False lets contact forces lift the holder; liquid coupling is enabled by default.
bowl = scene.add_entity(
    gs.morphs.USD(file=str(BOWL_USD),
                  pos=BOWL_POS, euler=BOWL_EULER, fixed=False, watertighten=None),
    material=gs.materials.Rigid(sdf_cell_size=0.001, sdf_min_res=64, sdf_max_res=256),
    surface=gs.surfaces.Default(color=(0.4, 0.8, 1.0)), name="Bowl",
)
if not args.no_liquid:
    liquid = scene.add_entity(
        material=gs.materials.SPH.Liquid(),
        morph=gs.morphs.Box(pos=LIQUID_POS, size=LIQUID_SIZE),
        surface=gs.surfaces.Default(color=(0.68, 0.62, 0.49), vis_mode="recon"),
    )
scene.build()

# Static visual marker for the scooping point; not a physical entity, so it
# can't collide with or obstruct the gripper.
if not args.headless:
    scene.draw_debug_sphere(pos=SCOOPING_POINT, radius=0.01, color=(1, 0, 0, 1))

# Fixed-base robot order: left arm 0:7, left fingers 7:9, right arm 9:16.
left_arm = np.arange(7)
left_finger = np.arange(7, 9)
right_arm = np.arange(9, 16)
openarm.set_dofs_kp(np.array([230, 230, 190, 190, 30, 30, 30, 30, 30,
                             230, 230, 190, 190, 30, 30, 30]))
openarm.set_dofs_kv(np.array([2.7, 2.7, 2.2, 2.2, 1.5, 1.5, 1.5, 0.2, 0.2,
                             2.7, 2.7, 2.2, 2.2, 1.5, 1.5, 1.5]))
force_limits = np.array([40, 40, 27, 27, 7, 7, 7, 10, 10, 40, 40, 27, 27, 7, 7, 7])
openarm.set_dofs_force_range(-force_limits, force_limits)
openarm.control_dofs_position(np.zeros(16))

# Read the existing grasp point from USD; Genesis IK takes its parent link + offset.
LEFT_GRIPPER_PATH = "/openarm_spoon/openarm_left_base_link/openarm_left_ee_base_link"
left_gripper = openarm.get_link(LEFT_GRIPPER_PATH)
stage = Usd.Stage.Open(str(OPENARM_USD))
xforms = UsdGeom.XformCache()
grip_to_link = (
    xforms.GetLocalToWorldTransform(stage.GetPrimAtPath(LEFT_GRIPPER_PATH + "/sites/left_gripper_grip_point"))
    * xforms.GetLocalToWorldTransform(stage.GetPrimAtPath(LEFT_GRIPPER_PATH)).GetInverse()
)
grip_local = np.array(grip_to_link.ExtractTranslation())

# Genesis' default (relative=True) getter removes its internal inertia-frame
# alignment, giving the moving USD frame needed for these STL-local coordinates.
def bowl_grasp_pose():
    rotation = Rotation.from_quat(bowl.get_quat().detach().cpu().numpy()[[1, 2, 3, 0]])
    position = bowl.get_pos().detach().cpu().numpy() + rotation.apply(BLOCK_GRASP_LOCAL)
    return position, rotation

grip_debug = None
target_debug = None
sim_step_count = 0

def grip_world_position():
    quat = left_gripper.get_quat(relative=False).detach().cpu().numpy()
    rotation = Rotation.from_quat(quat[[1, 2, 3, 0]])  # wxyz -> xyzw
    return left_gripper.get_pos(relative=False).detach().cpu().numpy() + rotation.apply(grip_local)


def step_and_draw():
    global grip_debug, target_debug, sim_step_count
    scene.step()
    sim_step_count += 1
    if args.headless:
        return
    if target_debug is not None:
        scene.clear_debug_object(target_debug)
    position, rotation = bowl_grasp_pose()
    frame = np.eye(4)
    frame[:3, :3] = rotation.as_matrix()
    frame[:3, 3] = position
    target_debug = scene.draw_debug_frame(T=frame, axis_length=0.06, origin_size=0.006,
                                         axis_radius=0.0015, color=(1, 0.25, 0, 1))
    if grip_debug is not None:
        scene.clear_debug_object(grip_debug)
    grip_debug = scene.draw_debug_sphere(pos=grip_world_position(), radius=0.005,
                                        color=(0, 1, 0, 0.8))


def move_to(qpos, steps=500):
    """Ramp joint targets (default 2 s), then settle for 0.4 s. No planning."""
    start = openarm.get_qpos().detach().cpu().numpy()
    qpos = qpos.detach().cpu().numpy() if hasattr(qpos, "detach") else np.asarray(qpos)
    for alpha in np.linspace(0, 1, steps):
        openarm.control_dofs_position(start + alpha * (qpos - start))
        step_and_draw()
    for _ in range(100):
        step_and_draw()


print("[Step 1] Raise left arm", flush=True)
# 1. Raise the left arm. Explicitly zero all other joint targets after IK.
qpos = openarm.inverse_kinematics_multilink(
    links=[left_gripper], local_points=[grip_local], dofs_idx_local=left_arm,
    poss=[[0.20, 0.30, 0.50]], quats=[[0.7071, 0, -0.7071, 0]],
    max_solver_iters=200, damping=0.001, pos_tol=1e-4, rot_tol=1e-3,
)
qpos[7:] = 0.0
move_to(qpos)

print("[Step 2] Open fingers", flush=True)
# 2. Open the fingers; keep the same left-arm target and right arm at zero.
gripper_open_pos = 0.4
qpos[left_finger] = gripper_open_pos
qpos[right_arm] = 0.0
move_to(qpos, steps=100)

# Refresh the target after the bowl and liquid have settled on the table.
grasp_target, bowl_rotation = bowl_grasp_pose()

print("[Step 3] Approach attachment", flush=True)
# 3. Move the grasp point to the attachment, keeping the fingers OPEN.
# Columns: gripper +X -> holder +Y; +Y -> holder -Z; +Z -> holder -X.
gripper_in_holder = np.column_stack(([0, 1, 0], [0, 0, -1], [-1, 0, 0]))
grasp_rotation = bowl_rotation * Rotation.from_matrix(gripper_in_holder)
# First align outside the free end, then insert horizontally between the open fingers.
# Holder +X runs from the free end toward the bowl.
approach = bowl_rotation.apply([0.06, 0, 0])
for target in (grasp_target - approach, grasp_target):
    qpos = openarm.inverse_kinematics_multilink(
        links=[left_gripper], local_points=[grip_local], dofs_idx_local=left_arm,
        poss=[target], quats=[grasp_rotation.as_quat()[[3, 0, 1, 2]]],
        max_solver_iters=200, damping=0.001, pos_tol=1e-4, rot_tol=1e-3,
    )
    qpos[7:] = 0.0
    qpos[left_finger] = gripper_open_pos
    move_to(qpos)

error_mm = 1000 * np.linalg.norm(grip_world_position() - grasp_target)
print(f"Grasp position error after settling: {error_mm:.2f} mm")

print("[Step 4] Close fingers", flush=True)
# 4. Grasp the holder by closing fingers; keep the same left-arm target and right arm at zero.
gripper_closed_pos = 0.0
qpos[left_finger] = gripper_closed_pos
qpos[right_arm] = 0.0
move_to(qpos, steps=100)

# Require contact on BOTH fingers. Closing the motor target alone does not attach a bowl.
contacts = openarm.get_contacts(with_entity=bowl)
touching_links = set(contacts["link_a"].tolist() + contacts["link_b"].tolist())
finger_links = {link.idx for link in openarm.links
                if link.name.endswith(("/openarm_left_ee_inner_finger", "/openarm_left_ee_outer_finger"))}
if len(finger_links) != 2 or not finger_links.issubset(touching_links):
    raise RuntimeError("Both fingers must contact the holder before lifting. Check the orange target and jaw clearance.")
bowl_start_z = bowl_grasp_pose()[0][2]

# Weld the bowl to the gripper so it can't slip or tilt in its jaws during the lift.
phase_start = time.perf_counter()
scene.sim.rigid_solver.add_weld_constraint(left_gripper.idx, bowl.base_link.idx)
report_phase("add_weld", phase_start)

print("[Step 5] Lift holder", flush=True)
# 5. Keep the fingers closed and lift the holder slightly.
# The SPH liquid follows through physical coupling; it is not parented to the gripper.
phase_start = time.perf_counter()
lift_target = grasp_target + np.array([0, 0, 0.10])
qpos = openarm.inverse_kinematics_multilink(
    links=[left_gripper], local_points=[grip_local], dofs_idx_local=left_arm,
    poss=[lift_target], quats=[grasp_rotation.as_quat()[[3, 0, 1, 2]]],
    max_solver_iters=200, damping=0.001, pos_tol=1e-4, rot_tol=1e-3,
)
qpos[7:] = 0.0
qpos[left_finger] = gripper_closed_pos
move_to(qpos)

report_phase("lift_ik_and_motion", phase_start)
bowl_lift = bowl_grasp_pose()[0][2] - bowl_start_z
print(f"Measured holder lift: {1000 * bowl_lift:.1f} mm (commanded gripper lift: 100 mm)")
if bowl_lift < 0.05:
    print("The holder did not follow the lift sufficiently; inspect the grasp for slipping.")

# 6. Replay the recorded marker trajectory. Each wrist's pose target is the rigid
# fit of its marker template to the recorded markers (five bowl markers on the
# left wrist via the weld, four spoon markers on the right). The whole joint
# trajectory is planned before playback (scooping_kinematics), then streamed.

# The spoon is rigid with the right wrist, so its marker offsets come straight
# from USD. The site Xform is identity -- the marker sphere nested under it
# carries the offset -- so resolve the child prim, not the site.
RIGHT_GRIPPER_PATH = "/openarm_spoon/openarm_right_base_link/openarm_right_ee_base_link"
right_gripper = openarm.get_link(RIGHT_GRIPPER_PATH)
SPOON_MARKER_COLUMNS = {"spoon_marker_1": "Spoon_front", "spoon_marker_2": "Spoon_back",
                        "spoon_marker_3": "Spoon_left", "spoon_marker_4": "Spoon_right"}
right_link_inv = xforms.GetLocalToWorldTransform(stage.GetPrimAtPath(RIGHT_GRIPPER_PATH)).GetInverse()
spoon_locals = [
    np.array((xforms.GetLocalToWorldTransform(
        stage.GetPrimAtPath(f"{RIGHT_GRIPPER_PATH}/sites/{marker}/{marker}"))
        * right_link_inv).ExtractTranslation())
    for marker in SPOON_MARKER_COLUMNS
]

# Holder sites are STL-local, the frame BLOCK_GRASP_LOCAL above is measured in.
# The rims share the CSV's names but not its numbering: the capture walks the rim
# in the opposite direction, so pairing them 1:1 warps the constellation by 37 mm
# and the IK cannot resolve an orientation. Reversing the rims fits it to 2.2 mm.
BOWL_MARKER_COLUMNS = {"Bowl_center": "Bowl_center", "Bowl_rim_1": "Bowl_rim_4",
                       "Bowl_rim_2": "Bowl_rim_3", "Bowl_rim_3": "Bowl_rim_2",
                       "Bowl_rim_4": "Bowl_rim_1"}
BOWL_ROOT_PATH = "/Bowl_holder_w_o_marker"
bowl_stage = Usd.Stage.Open(str(BOWL_USD))
bowl_xforms = UsdGeom.XformCache()
bowl_root_inv = bowl_xforms.GetLocalToWorldTransform(bowl_stage.GetPrimAtPath(BOWL_ROOT_PATH)).GetInverse()
bowl_marker_local = [
    np.array((bowl_xforms.GetLocalToWorldTransform(
        bowl_stage.GetPrimAtPath(f"{BOWL_ROOT_PATH}/sites/{site}")) * bowl_root_inv).ExtractTranslation())
    for site in BOWL_MARKER_COLUMNS
]

# The weld pins the holder in the jaws, so the bowl markers are now rigid with
# the left wrist too. Freeze them into that wrist's frame once, as actually
# grasped, and reuse them as IK local points for the whole replay.
# relative=False is the solver's own link frame, the one IK local points use.
held_link_pos = left_gripper.get_pos(relative=False).detach().cpu().numpy()
held_link_rot = Rotation.from_quat(left_gripper.get_quat(relative=False).detach().cpu().numpy()[[1, 2, 3, 0]])
held_bowl_pos, held_bowl_rot = bowl.get_pos().detach().cpu().numpy(), bowl_grasp_pose()[1]
bowl_locals = [held_link_rot.inv().apply(held_bowl_pos + held_bowl_rot.apply(offset) - held_link_pos)
               for offset in bowl_marker_local]

MARKER_COLUMNS = list(BOWL_MARKER_COLUMNS.values()) + list(SPOON_MARKER_COLUMNS.values())
if MARKER_COLUMNS != sk.BOWL_NAMES + sk.SPOON_NAMES:
    raise ValueError("Marker order differs from the planner's CSV order")
trajectory_times, trajectory = sk.mapped_targets(SCOOPING_POINT)
task_end = sk.task_frames(trajectory)
if args.max_frames is not None:
    if args.max_frames < 2:
        raise ValueError("--max-frames must be at least 2")
    task_end = min(task_end, args.max_frames)
trajectory_times, trajectory = trajectory_times[:task_end], trajectory[:task_end]
frame_dt = trajectory_times[1] - trajectory_times[0]
if not np.isfinite(trajectory).all() or not np.all(np.diff(trajectory_times) > 0):
    raise ValueError("Trajectory must contain finite positions and increasing timestamps")
print(f"[Step 6] Scooping point {SCOOPING_POINT.tolist()}; replaying 0-{trajectory_times[-1]:.2f} s "
      "(ends once the spoon has lifted clear of the bowl)", flush=True)

# Plan the whole joint trajectory before playback, from the grasp actually achieved.
phase_start = time.perf_counter()
kins = (sk.ArmKinematics('left'), sk.ArmKinematics('right'))
current_q = openarm.get_qpos().detach().cpu().numpy()
plans, plan_metrics = sk.plan_trajectory(trajectory_times, trajectory, np.array(bowl_locals),
                                         np.array(spoon_locals), current_q, kins)
report_phase("trajectory_plan", phase_start)
for side, metric in zip(("left/bowl", "right/spoon"), plan_metrics):
    print(f"  {side}: IK max {metric['max_pos_err_mm']:.1f} mm / {metric['max_rot_err_deg']:.2f} deg "
          f"({metric['failing_frames']} frames over {1e3 * sk.POS_TOL:.0f} mm / {np.rad2deg(sk.ROT_TOL):.0f} deg), "
          f"limit margin {metric['min_limit_margin_deg']:.1f} deg, peak {metric['max_vel_rad_s']:.2f} rad/s", flush=True)
low, high = (x.detach().cpu().numpy() for x in openarm.get_dofs_limit())
dense_times = trajectory_times[0] + scene.sim.dt * np.arange(1, round((trajectory_times[-1] - trajectory_times[0]) / scene.sim.dt) + 1)
joint_plan = np.tile(current_q, (len(dense_times) + 1, 1))
joint_plan[:, left_arm] = plans[0]['spline'](np.r_[trajectory_times[0], dense_times])
joint_plan[:, right_arm] = plans[1]['spline'](np.r_[trajectory_times[0], dense_times])
joint_plan[:, left_finger] = gripper_closed_pos
arm_dofs = np.r_[left_arm, right_arm]
if np.any(joint_plan[:, arm_dofs] < low[arm_dofs]) or np.any(joint_plan[:, arm_dofs] > high[arm_dofs]):
    raise RuntimeError("Planned joint trajectory leaves the joint limits; refusing to execute")
# Unreachable samples are not retried: the best residual is reported above and
# executed as planned, so any shortfall stays visible rather than hidden.
if any(m['failing_frames'] for m in plan_metrics):
    print("  WARNING: some samples exceed the IK tolerance; executing the best achievable plan.", flush=True)

planned_markers = np.array([np.r_[sk.marker_positions(kins[0], plans[0]['spline'](t), bowl_locals),
                                  sk.marker_positions(kins[1], plans[1]['spline'](t), spoon_locals)]
                            for t in trajectory_times])
planned_residual = np.concatenate([planned_markers - trajectory, np.zeros_like(trajectory)], axis=2)

recorder = None
if args.diagnostics:
    recorder = Recorder(args.diagnostics, {"bowl": bowl_marker_local, "spoon": spoon_locals},
                        dict(trajectory=str(TRAJ_CSV), scooping_point=SCOOPING_POINT.tolist(),
                             task_end_s=float(trajectory_times[-1]), headless=args.headless, liquid=not args.no_liquid,
                             dt=scene.sim.dt, substeps=scene.sim.substeps, pos_tol_m=sk.POS_TOL,
                             plan=plan_metrics, playback="precomputed joint spline, one target per physics step",
                             pose_definition="Marker centroid + rotation from USD template; quaternion xyzw",
                             joint_order="left arm 0:7; fingers 7:9; right arm 9:16",
                             status_definition="Planned marker residual <= POS_TOL for every marker"))
    atexit.register(recorder.finish)
    for phase, seconds in phase_timings: recorder.event(phase, seconds)


def marker_world_positions():
    """Where the tracked markers actually ended up, in the solver's world frame."""
    positions = []
    for link, offsets in ((left_gripper, bowl_locals), (right_gripper, spoon_locals)):
        origin = link.get_pos(relative=False).detach().cpu().numpy()
        rotation = Rotation.from_quat(link.get_quat(relative=False).detach().cpu().numpy()[[1, 2, 3, 0]])
        positions.extend(origin + rotation.apply(offset) for offset in offsets)
    return np.array(positions)


def actual_marker_positions():
    """Use the physical bowl pose, not the wrist/weld assumption, for bowl errors."""
    positions = marker_world_positions()
    rotation = bowl_grasp_pose()[1]
    origin = bowl.get_pos().detach().cpu().numpy()
    positions[:5] = origin + rotation.apply(bowl_marker_local)
    return positions


def record_sample(index, command, physics_wall):
    if recorder:
        recorder.sample(index, trajectory_times[index], sim_step_count * scene.sim.dt,
                        trajectory[index], actual_marker_positions(), marker_world_positions()[:5],
                        command, openarm.get_qpos(), planned_residual[index], 0.0, physics_wall,
                        (low, high), openarm.get_dofs_control_force(), force_limits)
        # Rigid contact forces identify obstacles/other-arm contacts separately
        # from PD tracking. SPH coupling forces are not included in this API.
        contacts = bowl.get_contacts()
        groups = {}
        for a, b, force in zip(contacts["link_a"].tolist(), contacts["link_b"].tolist(),
                               contacts["force_a"].detach().cpu().numpy()):
            pair = (scene.rigid_solver.links[a].name, scene.rigid_solver.links[b].name)
            count, total, maximum = groups.get(pair, (0, np.zeros(3), 0.0))
            groups[pair] = (count + 1, total + force, max(maximum, float(np.linalg.norm(force))))
        for (a, b), (count, total, maximum) in groups.items():
            recorder.write('bowl_contacts.csv', dict(index=index, trajectory_time_s=trajectory_times[index],
                           link_a=a, link_b=b, count=count, force_on_a_x_N=total[0],
                           force_on_a_y_N=total[1], force_on_a_z_N=total[2], max_contact_force_N=maximum))


transition, clearance = sk.plan_transition(kins, current_q, joint_plan[0], bowl_locals, spoon_locals)
print(f"  transition: lift {clearance['lift_m']:.2f} m, table clearance {1e3 * clearance['table_clearance_m']:.0f} mm, "
      f"spoon-bowl separation {1e3 * clearance['spoon_bowl_separation_m']:.0f} mm", flush=True)
if recorder: recorder.event('transition', clearance)
started = time.perf_counter()
for command in transition:
    openarm.control_dofs_position(command)
    step_and_draw()
for _ in range(100):
    step_and_draw()
record_sample(0, joint_plan[0], time.perf_counter() - started)

# Continuous playback: a new interpolated target every physics step, no IK.
# Samples are recorded at every second CSV frame, as before, for comparison.
TRAJ_STRIDE = 2
sample_at_step = {round((trajectory_times[i] - trajectory_times[0]) / scene.sim.dt): i
                  for i in range(TRAJ_STRIDE, len(trajectory), TRAJ_STRIDE)}
worst_error = np.zeros(2)
traj_debug = None
started = time.perf_counter()
for step, command in enumerate(joint_plan[1:], start=1):
    openarm.control_dofs_position(command)
    step_and_draw()
    if recorder:
        recorder.joints(int((dense_times[step - 1] - trajectory_times[0]) / frame_dt), dense_times[step - 1],
                        sim_step_count * scene.sim.dt,
                        command, openarm.get_qpos())
    index = sample_at_step.get(step)
    if index is None:
        continue
    record_sample(index, command, time.perf_counter() - started)
    started = time.perf_counter()
    error = np.linalg.norm(actual_marker_positions() - trajectory[index], axis=1)
    worst_error = np.maximum(worst_error, [error[:5].max(), error[5:].max()])
    if not args.headless:
        if traj_debug is not None:
            scene.clear_debug_object(traj_debug)
        traj_debug = scene.draw_debug_spheres(poss=trajectory[index], radius=0.005, color=(1, 0.9, 0.2, 0.6))
    if index % 100 == 0:
        print(f'[Replay] frame {index}, t={trajectory_times[index]:.2f}s, '
              f'max marker error={1000*error.max():.1f}mm', flush=True)

print(f"Worst actual marker error during replay: bowl {1000 * worst_error[0]:.1f} mm, "
      f"spoon {1000 * worst_error[1]:.1f} mm")
if recorder:
    recorder.finish()
    atexit.unregister(recorder.finish)
    print(f'Diagnostics saved to {args.diagnostics.resolve()}', flush=True)

# Hold the final (lifted-clear) pose.
while not args.headless and scene.viewer.is_alive():
    step_and_draw()
